/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicionet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

/**
 *
 * @author at10DAM2
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Vehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVehiculos = new javax.swing.ButtonGroup();
        grupoCaracteristicas = new javax.swing.ButtonGroup();
        grupoCombustible = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cajaMarca = new javax.swing.JTextField();
        cajaModelo = new javax.swing.JTextField();
        terxtoModelo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        checkCoche = new javax.swing.JCheckBox();
        checkMoto = new javax.swing.JCheckBox();
        checkCamion = new javax.swing.JCheckBox();
        botonSacarInfo = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        checkRemolque = new javax.swing.JCheckBox();
        checkCapota = new javax.swing.JCheckBox();
        checkSidecar = new javax.swing.JCheckBox();
        radioGasolina = new javax.swing.JRadioButton();
        radioDiesel = new javax.swing.JRadioButton();
        radioElectrico = new javax.swing.JRadioButton();
        comboBoxColor = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        textoNombre = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();
        menuBarraArchivo = new javax.swing.JMenu();
        menuBarraProducto = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cajaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMarcaActionPerformed(evt);
            }
        });

        terxtoModelo.setText("Modelo");

        jLabel1.setText("Marca");

        grupoVehiculos.add(checkCoche);
        checkCoche.setText("Coche");
        checkCoche.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkCocheItemStateChanged(evt);
            }
        });
        checkCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkCocheMouseClicked(evt);
            }
        });
        checkCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCocheActionPerformed(evt);
            }
        });

        grupoVehiculos.add(checkMoto);
        checkMoto.setText("Moto");
        checkMoto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkMotoItemStateChanged(evt);
            }
        });
        checkMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMotoMouseClicked(evt);
            }
        });
        checkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoActionPerformed(evt);
            }
        });

        grupoVehiculos.add(checkCamion);
        checkCamion.setText("Camion");
        checkCamion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkCamionItemStateChanged(evt);
            }
        });
        checkCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkCamionMouseClicked(evt);
            }
        });
        checkCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCamionActionPerformed(evt);
            }
        });

        botonSacarInfo.setText("Sacar info");
        botonSacarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSacarInfoMouseClicked(evt);
            }
        });
        botonSacarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSacarInfoActionPerformed(evt);
            }
        });

        botonReset.setText("Reset");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        grupoCaracteristicas.add(checkRemolque);
        checkRemolque.setText("Remolque");

        grupoCaracteristicas.add(checkCapota);
        checkCapota.setText("Capota");
        checkCapota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCapotaActionPerformed(evt);
            }
        });

        grupoCaracteristicas.add(checkSidecar);
        checkSidecar.setText("Sidecar");
        checkSidecar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkSidecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSidecarActionPerformed(evt);
            }
        });

        grupoCombustible.add(radioGasolina);
        radioGasolina.setText("Gasolina");
        radioGasolina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioGasolinaMouseClicked(evt);
            }
        });

        grupoCombustible.add(radioDiesel);
        radioDiesel.setText("Diesel");
        radioDiesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioDieselMouseClicked(evt);
            }
        });

        grupoCombustible.add(radioElectrico);
        radioElectrico.setText("Eléctrico");
        radioElectrico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioElectricoMouseClicked(evt);
            }
        });

        comboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Amarillo", "Verde", "Rojo", "Blanco", "Negro" }));
        comboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxColor(evt);
            }
        });

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Modelo", "Vehiculo", "Extra", "Combustible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVehiculos);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        textoNombre.setText("Nombre");

        botonBorrar.setText("Borrar líneas");
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarMouseClicked(evt);
            }
        });
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarMouseClicked(evt);
            }
        });
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        menuBarraArchivo.setText("Archivos");

        menuBarraProducto.setText("Producto");
        menuBarraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarraProductoActionPerformed(evt);
            }
        });
        menuBarraArchivo.add(menuBarraProducto);

        menuBarra.add(menuBarraArchivo);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cajaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cajaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(terxtoModelo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonSacarInfo)
                        .addGap(18, 18, 18)
                        .addComponent(botonReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkCoche)
                        .addGap(18, 18, 18)
                        .addComponent(checkMoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkCamion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRemolque)
                            .addComponent(radioGasolina))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkCapota)
                            .addComponent(radioDiesel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioElectrico)
                            .addComponent(checkSidecar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoNombre)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terxtoModelo)
                    .addComponent(jLabel1)
                    .addComponent(textoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar)
                    .addComponent(botonActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkCoche)
                            .addComponent(checkMoto)
                            .addComponent(checkCamion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkRemolque)
                            .addComponent(checkCapota)
                            .addComponent(checkSidecar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioGasolina)
                            .addComponent(radioDiesel)
                            .addComponent(radioElectrico))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSacarInfo)
                            .addComponent(botonReset)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            // Devuelven un int:
        //  0 - Aceptar, Sí
        //  1 - No
        //  2 - Cancelar
   
    private void cajaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMarcaActionPerformed

    private void checkCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCocheActionPerformed
      
    }//GEN-LAST:event_checkCocheActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea RESETEAR?",
                "OK_CANCEL_OPTION", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (respuesta == 0){
            grupoVehiculos.clearSelection();
            grupoCaracteristicas.clearSelection();
            checkSidecar.setEnabled(true);
            checkCapota.setEnabled(true);
            checkRemolque.setEnabled(true);
            grupoCombustible.clearSelection();
            cajaMarca.setText("");
            cajaModelo.setText("");
            txtNombre.setText("");
            JOptionPane.showMessageDialog(null, "Usted ha decidido resetear",
                    "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_botonResetActionPerformed

    private void checkCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCamionActionPerformed

    private void checkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMotoActionPerformed

    private void checkMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMotoMouseClicked
        if (checkMoto.isSelected()){
            checkCoche.setSelected(false);
            checkCamion.setSelected(false);
        }
    }//GEN-LAST:event_checkMotoMouseClicked

    private void checkCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCocheMouseClicked
        if (checkCoche.isSelected()){
            checkMoto.setSelected(false);
            checkCamion.setSelected(false);
        }
    }//GEN-LAST:event_checkCocheMouseClicked

    private void checkCamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCamionMouseClicked
        if (checkCamion.isSelected()){
            checkCoche.setSelected(false);
            checkMoto.setSelected(false);
        }
    }//GEN-LAST:event_checkCamionMouseClicked

    private void botonSacarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSacarInfoActionPerformed
        DefaultTableModel modeloDatos = (DefaultTableModel)tblVehiculos.getModel();
        String vehiculo = "";
        if (checkCoche.isSelected()){
            vehiculo = "Coche"; 
        } else if (checkMoto.isSelected()){
            vehiculo = "Moto"; 
        } else if (checkCamion.isSelected()){
            vehiculo = "Camion"; 
        };
        String extra = "";
        if (checkRemolque.isSelected()){
            extra = "Remolque"; 
        } else if (checkCapota.isSelected()){
            extra = "Capota"; 
        } else if (checkSidecar.isSelected()){
            extra = "Sidecar"; 
        };
        String carburante = "";
        if (radioGasolina.isSelected()){
            carburante = "Gasolina"; 
        } else if (radioElectrico.isSelected()){
            carburante = "Electrico"; 
        } else if (radioDiesel.isSelected()){
            carburante = "Diesel"; 
        };
        
        modeloDatos.addRow(new Object[]{txtNombre.getText(),cajaMarca.getText(),cajaModelo.getText(),vehiculo,extra,carburante});
    }//GEN-LAST:event_botonSacarInfoActionPerformed

    private void checkCocheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkCocheItemStateChanged
        if (checkCoche.isSelected()) {
            checkCapota.setEnabled(true);
            checkRemolque.setEnabled(true);
            checkSidecar.setEnabled(false);
        }
    }//GEN-LAST:event_checkCocheItemStateChanged

    private void checkMotoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkMotoItemStateChanged
        if (checkMoto.isSelected()) {
            checkSidecar.setEnabled(true);
            checkCapota.setEnabled(false);
            checkRemolque.setEnabled(false);
        }
    }//GEN-LAST:event_checkMotoItemStateChanged

    private void checkCamionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkCamionItemStateChanged
        if (checkCamion.isSelected()) {
        checkRemolque.setEnabled(true);
        checkCapota.setEnabled(false);
        checkSidecar.setEnabled(false);
        }
    }//GEN-LAST:event_checkCamionItemStateChanged

    private void botonSacarInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSacarInfoMouseClicked
        JOptionPane.showMessageDialog(null, "Modelo: " + cajaModelo.getText() + " Marca: " + cajaMarca.getText());
        
        if (checkCoche.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted tiene un coche");
        } else if (checkMoto.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted tiene una moto");
        } else if (checkCamion.isSelected()){
            JOptionPane.showMessageDialog(null, "Usted tiene un camion");}
        
        if (checkRemolque.isSelected()){
            JOptionPane.showMessageDialog(null, "Tambien seleccionado un remolque");
        } else if (checkCapota.isSelected()){
            JOptionPane.showMessageDialog(null, "Tambien seleccionado una capota");
        } else if (checkSidecar.isSelected()){JOptionPane.showMessageDialog(null, "Tambien seleccionado un sidecar");}
        
        if (radioGasolina.isSelected()){
            JOptionPane.showMessageDialog(null, "Combustible: Gasolina");
        } else if (radioDiesel.isSelected()){
            JOptionPane.showMessageDialog(null, "Combustible: Diesel");
        } else if (radioElectrico.isSelected()){JOptionPane.showMessageDialog(null, "Combustible: Electrico");}
        
        JOptionPane.showMessageDialog(null, "Color del vehículo: " + comboBoxColor.getSelectedItem().toString());
    }//GEN-LAST:event_botonSacarInfoMouseClicked

    private void radioElectricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioElectricoMouseClicked
        if (radioElectrico.isSelected()){
            radioGasolina.setSelected(false);
            radioDiesel.setSelected(false);
        }
    }//GEN-LAST:event_radioElectricoMouseClicked

    private void radioDieselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioDieselMouseClicked
        if (radioDiesel.isSelected()){
            radioGasolina.setSelected(false);
            radioElectrico.setSelected(false);
        }
    }//GEN-LAST:event_radioDieselMouseClicked

    private void radioGasolinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioGasolinaMouseClicked
        if (radioGasolina.isSelected()){
            radioDiesel.setSelected(false);
            radioElectrico.setSelected(false);
        }
    }//GEN-LAST:event_radioGasolinaMouseClicked

    private void comboBoxColor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxColor
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxColor

    private void checkSidecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSidecarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSidecarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        DefaultTableModel modeloDatos = (DefaultTableModel)tblVehiculos.getModel();
    
        try {
            int filaSeleccionada = tblVehiculos.getSelectedRow();
            modeloDatos.removeRow(filaSeleccionada);
        } catch (ArrayIndexOutOfBoundsException error) {
        
        if (tblVehiculos.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No hay registros disponibles.",
                "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR intenado borrar linea: " + error.getMessage());
        };
        // Expected output: ReferenceError: nonExistentFunction is not defined
        // (Note: the exact output may be browser-dependent)
      } 
       
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseClicked
         
    }//GEN-LAST:event_botonBorrarMouseClicked

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        txtNombre.setText(String.valueOf(tblVehiculos.getValueAt(tblVehiculos.getSelectedRow(), tblVehiculos.getSelectedColumn())));
    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseClicked
       tblVehiculos.setValueAt(txtNombre.getText(), tblVehiculos.getSelectedRow(), tblVehiculos.getSelectedColumn());
    }//GEN-LAST:event_botonActualizarMouseClicked

    private void menuBarraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraProductoActionPerformed
        Producto prod = new Producto() ;
        prod.setVisible (true); // TODO add your handling code here:
    }//GEN-LAST:event_menuBarraProductoActionPerformed

    private void checkCapotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCapotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCapotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonSacarInfo;
    private javax.swing.JTextField cajaMarca;
    private javax.swing.JTextField cajaModelo;
    private javax.swing.JCheckBox checkCamion;
    private javax.swing.JCheckBox checkCapota;
    private javax.swing.JCheckBox checkCoche;
    private javax.swing.JCheckBox checkMoto;
    private javax.swing.JCheckBox checkRemolque;
    private javax.swing.JCheckBox checkSidecar;
    private javax.swing.JComboBox<String> comboBoxColor;
    private javax.swing.ButtonGroup grupoCaracteristicas;
    private javax.swing.ButtonGroup grupoCombustible;
    private javax.swing.ButtonGroup grupoVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu menuBarraArchivo;
    private javax.swing.JMenuItem menuBarraProducto;
    private javax.swing.JRadioButton radioDiesel;
    private javax.swing.JRadioButton radioElectrico;
    private javax.swing.JRadioButton radioGasolina;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JLabel terxtoModelo;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
