/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.miprimeraapp;

/**
 *
 * @author at10DAM2
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        saludarBotom = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        boxFresa = new javax.swing.JCheckBox();
        boxChocolate = new javax.swing.JCheckBox();
        boxVainilla = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saludarBotom.setBackground(new java.awt.Color(0, 153, 255));
        saludarBotom.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        saludarBotom.setForeground(new java.awt.Color(255, 255, 255));
        saludarBotom.setText("Saludar");
        saludarBotom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saludarBotomMouseClicked(evt);
            }
        });
        saludarBotom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saludarBotomActionPerformed(evt);
            }
        });

        LabelNombre.setText("Nombre");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        boxFresa.setLabel("Fresa");
        boxFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFresaActionPerformed(evt);
            }
        });

        boxChocolate.setActionCommand("Chocolate");
        boxChocolate.setLabel("Chocolate");
        boxChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxChocolateActionPerformed(evt);
            }
        });

        boxVainilla.setLabel("Vainilla");
        boxVainilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxVainillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxFresa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saludarBotom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(boxChocolate)
                    .addComponent(boxVainilla))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saludarBotom))
                .addGap(29, 29, 29)
                .addComponent(boxFresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxChocolate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxVainilla)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void saludarBotomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saludarBotomActionPerformed
        String frase = "";
        if (boxFresa.isSelected()){
            frase = " fresa";
        }
        if (boxChocolate.isSelected()){
            frase = frase + " chocolate";
        }
        if (boxVainilla.isSelected()){
            frase = frase + " vainilla";
        }
        System.out.println("Hola, mi nombre es " + campoNombre.getText() + " y me gustan los helados de" + frase + ".");
    }//GEN-LAST:event_saludarBotomActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void saludarBotomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saludarBotomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saludarBotomMouseClicked

    private void boxFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFresaActionPerformed

    private void boxChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxChocolateActionPerformed

    private void boxVainillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxVainillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxVainillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JCheckBox boxChocolate;
    private javax.swing.JCheckBox boxFresa;
    private javax.swing.JCheckBox boxVainilla;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton saludarBotom;
    // End of variables declaration//GEN-END:variables
}
